import type { SupportedLocale } from "@/lib/i18n/locales";

export const firstOrderCopy = {
  tr: {
    actionErrors: {
      acceptFailed: "İlk sipariş kabul edilirken bir sorun oluştu.",
      factoryMissing: "Fabrika bulunamadı. Önce onboarding akışını tamamla.",
      firstProductionMissing: "İlk sipariş üretim kaydı bulunamadı.",
      matchingLineMissing: "Üretim rotası için uygun fabrika hattı bulunamadı.",
      optionMissing: "Seçilen ilk sipariş ürünü artık kullanılamıyor.",
      optionRequired: "Sipariş seçimi zorunlu.",
      routeMissing: "Bu ürünün üretim rotası tanımlanmamış.",
    },
    selection: {
      emptyKicker: "ORDER MARKET",
      emptyTitle: "İlk sipariş bulunamadı",
      emptyBody: "Admin panelinden bu sektör için 3 aktif ilk sipariş ürünü tanımlandığında bu ekran açılacak.",
      marketKicker: "ORDER MARKET",
      title: "İlk Siparişini Seç",
      deliveryPrefix: "Teslim",
      footerTitle: "Sipariş seçilirse üretim emri hazırlanacak.",
      footerBody: "Kabulden sonra ilk 3 günlük simülasyon akışına geçeceğiz.",
      selectedKicker: "SEÇİLİ SİPARİŞ",
      offers: (count: number) => `${count} teklif`,
      routePending: "Rota bekleniyor",
      statusOpen: "Teklif açık",
      quantity: (value: string) => `${value} adet`,
      deliveryDays: (days: number) => `${days} gün`,
      requestedDay: (day: number) => `Day ${day}`,
      meta: {
        code: "Kod",
        requestedDate: "İstenen Tarih",
        quantity: "Sipariş Adedi",
        unitPrice: "Birim Fiyat",
        totalPrice: "Sipariş Tutarı",
        route: "Üretim Rotası",
      },
      preparing: "Hazırlanıyor...",
      accept: "Siparişi kabul et",
    },
    productTier: {
      BASIC: "Kolay",
      STANDARD: "Orta",
      PREMIUM: "Zor",
      LUXURY: "Uzman",
    },
    simulation: {
      headerKicker: "FIRST SHIFT SIMULATION",
      dayCopy: [
        {
          eyebrow: "DAY 1",
          title: "Kesim başlıyor",
          body: "İlk vardiya kumaşı üretime hazır parçalara ayırır.",
        },
        {
          eyebrow: "DAY 2",
          title: "Kesim ve dikim birlikte çalışır",
          body: "Kesilen parçalar dikime akar; iki hat aynı anda üretim sayar.",
        },
        {
          eyebrow: "DAY 3",
          title: "Ütü / paket devreye girer",
          body: "Dikimden çıkan ürünler son operasyona girer; sipariş kuyruğu gerçek kapasiteyle ilerler.",
        },
      ],
      completeProgress: "3 / 3 gün tamamlandı",
      runningProgress: (day: number) => `${day}. gün vardiyası çalışıyor`,
      progress: (completed: number) => `${completed} / 3 gün tamamlandı`,
      dashboardCta: "Dashboard ekranına geç",
      xpAdded: (xp: number) => `+${xp} XP cüzdana eklenir`,
      running: "Çalışıyor",
      startShift: "Vardiya Başlat",
      metricLabels: ["Kesilen ad.", "Dikilen ad.", "Ütülenen ad."],
      orderQuantityMetric: "Sip Ad.",
      segment: "Segment",
      segmentLabel: (grade: string) => `${grade} Segment`,
      activeProduction: "Vardiya üretimi",
      totalProduction: "Toplam üretim",
      pieceUnit: "adet",
      lineImageAlt: (name: string) => `${name} üretim hattı`,
    },
  },
  en: {
    actionErrors: {
      acceptFailed: "Something went wrong while accepting the first order.",
      factoryMissing: "Factory was not found. Complete onboarding first.",
      firstProductionMissing: "First-order production record was not found.",
      matchingLineMissing: "No matching factory line was found for the production route.",
      optionMissing: "The selected first-order product is no longer available.",
      optionRequired: "Order selection is required.",
      routeMissing: "This product does not have a production route.",
    },
    selection: {
      emptyKicker: "ORDER MARKET",
      emptyTitle: "No first order found",
      emptyBody: "This screen opens when 3 active first-order products are defined for this sector in the admin panel.",
      marketKicker: "ORDER MARKET",
      title: "Choose Your First Order",
      deliveryPrefix: "Delivery",
      footerTitle: "A production order will be prepared after you choose an order.",
      footerBody: "After acceptance, you will move into the first 3-day simulation flow.",
      selectedKicker: "SELECTED ORDER",
      offers: (count: number) => `${count} offers`,
      routePending: "Route pending",
      statusOpen: "Offer open",
      quantity: (value: string) => `${value} pcs`,
      deliveryDays: (days: number) => `${days} days`,
      requestedDay: (day: number) => `Day ${day}`,
      meta: {
        code: "Code",
        requestedDate: "Requested Date",
        quantity: "Order Quantity",
        unitPrice: "Unit Price",
        totalPrice: "Order Total",
        route: "Production Route",
      },
      preparing: "Preparing...",
      accept: "Accept order",
    },
    productTier: {
      BASIC: "Easy",
      STANDARD: "Medium",
      PREMIUM: "Hard",
      LUXURY: "Expert",
    },
    simulation: {
      headerKicker: "FIRST SHIFT SIMULATION",
      dayCopy: [
        {
          eyebrow: "DAY 1",
          title: "Cutting starts",
          body: "The first shift turns fabric into production-ready pieces.",
        },
        {
          eyebrow: "DAY 2",
          title: "Cutting and sewing work together",
          body: "Cut pieces flow into sewing; two lines count production at the same time.",
        },
        {
          eyebrow: "DAY 3",
          title: "Ironing / packing comes online",
          body: "Sewn products enter the final operation; the order queue moves with real capacity.",
        },
      ],
      completeProgress: "3 / 3 days completed",
      runningProgress: (day: number) => `Day ${day} shift is running`,
      progress: (completed: number) => `${completed} / 3 days completed`,
      dashboardCta: "Go to dashboard",
      xpAdded: (xp: number) => `+${xp} XP added to wallet`,
      running: "Running",
      startShift: "Start Shift",
      metricLabels: ["Cut pcs", "Sewn pcs", "Ironed pcs"],
      orderQuantityMetric: "Order Qty",
      segment: "Segment",
      segmentLabel: (grade: string) => `${grade} Segment`,
      activeProduction: "Shift output",
      totalProduction: "Total output",
      pieceUnit: "pcs",
      lineImageAlt: (name: string) => `${name} production line`,
    },
  },
} as const satisfies Record<SupportedLocale, unknown>;

export type FirstOrderCopy = (typeof firstOrderCopy)[SupportedLocale];
